### ISSUE TITLE
Invert the "stable" feature into an "unstable" feature

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#1]
The current cfg situation is:

```rust
#[path = "stable.rs"]
#[cfg(feature = "stable")]
mod imp;
#[path = "unstable.rs"]
#[cfg(not(feature = "stable"))]
mod imp;
```

This is annoying because it requires every library that transitively depends on proc-macro2 to provide its own "stable" cfg that mirrors proc-macro2's "stable" cfg. If I want to use nightly with nice errors in my app, I need to track down the "stable" cfg of every single library in my dependency graph that uses proc-macro2, and disable the "stable" cfg of each one individually.

Inverting this to an "unstable" feature means that libraries using proc-macro2 do not need a cfg at all. The end user can opt into nightly by adding their own dependency on proc-macro2 that sets the unstable cfg.

**Comment by alexcrichton** [comment]
Yeah in retrospect I'm not sure what I was thinking.

The downside is that we have to unconditionally depend on synom/unicode-xid as a result, but that's not really too bad in the grand scheme of things.
