### ISSUE TITLE
Punctuation not always recognized as joint

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#10]
It looks like punctuation is only recognized as joint if it begins a sequence of punctuation to which Rust assigns meaning.

This is not my interpretation of https://github.com/rust-lang/rust/pull/40939 and if it is intentional, I would object to that behavior. A punctuation should be joint if it is followed immediately by other punctuation.

```rust
"++".parse::<TokenStream>().unwrap()
```

```
TokenStream(
    TokenStream {
        inner: [
            TokenTree {
                span: Span(
                    Span
                ),
                kind: Op(
                    '+',
                    Alone
                )
            },
            TokenTree {
                span: Span(
                    Span
                ),
                kind: Op(
                    '+',
                    Alone
                )
            }
        ]
    }
)
```

**Comment by mystor** [comment]
I've written some code for this over at https://github.com/mystor/fauxenstream

**Comment by mystor** [comment]
(probably not super useful here but if you want feel free to take it)
