### ISSUE TITLE
`Tokens` previously implemented `Default` but `TokenStream` no longer does

### ISSUE THREAD

**Issue by H2CO3** [alexcrichton/proc-macro2#105]
It made perfect sense for it to create an empty token stream. In my specific use case, I have a 3-tuple of `TokenStream`s that I could previously default-initialize using `Default::default()`, but now I have to write `(TokenStream::new(), TokenStream::new(), TokenStream::new())`.

**Comment by alexcrichton** [comment]
Sounds reasonable to me to add!

**Comment by H2CO3** [comment]
Awesome, btw I'm already working on the PR :)
