### ISSUE TITLE
Runtime dependency on proc-macro2 can result in binary that can't be run

### ISSUE THREAD

**Issue by davidlattimore** [alexcrichton/proc-macro2#115]
I have a crate I'm developing that uses the syn crate, which in turn uses proc-macro2. My crate is not a procedural macro, but a regular binary that needs facilities for parsing Rust source (it's a REPL).

By setting default-features = false when I depend on proc-macro2, syn, failure etc, my crate can currently be compiled on stable rust and run normally.

However it seems that if any of my downstream dependencies were to start using custom derive (e.g. from the failure crate), then that turns on the "proc-macro" feature and I end up with a binary that dynamically links libstd (and possibly libprocmacro) and so is unable to be run (except via cargo run or LD_LIBRARY_PATH etc).

I hope what I've said make sense, I'm a little fuzzy on it myself. I've attached a minimal repro.

[procmacro.zip](https://github.com/alexcrichton/proc-macro2/files/2282601/procmacro.zip)

If I run:
cd aaa
cargo build --release
./target/release/aaa

Then I get:

./target/release/aaa: error while loading shared libraries: libstd-0cce0e0e34e933aa.so: cannot open shared object file: No such file or directory

If I delete the dependency on failure from crate "bbb" then I get a binary that runs OK.

This is with stable rust 1.28.0.

I understand that the primary use case of this crate and crates like syn is for use in procedural macros, but there are bunch of other useful uses I can see, so I'm hoping this can work. In any case, it seems odd that I can produce a binary using --release on the stable compiler that then doesn't run.

**Comment by dtolnay** [comment]
This issue is being tracked in https://github.com/rust-lang/rust/issues/45601 with a fix in progress in https://github.com/rust-lang/rust/pull/49219. It is not something that can be fixed in proc-macro2 so let's continue to track it over there. Thanks!
