### ISSUE TITLE
Panic message printed even when stable shim is working

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#122]
```toml
[dependencies]
proc-macro2 = "0.4"
```

```rust
extern crate proc_macro2;

fn main() {
    proc_macro2::Span::call_site();
    println!("ran anyway");
}
```

Running this crate as of proc-macro2 0.4.15 and rustc 1.30.0-nightly (02cb8f2a4 2018-08-29) results in the following output being printed:

```console
thread 'main' panicked at 'procedural macro API is used outside of a procedural macro', libproc_macro/lib.rs:1294:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
ran anyway
```

Is there any way we can do the `nightly_works()` check without a panic being printed?

https://github.com/dtolnay/syn/issues/475 @djmcgill

**Comment by alexcrichton** [comment]
Id love to fix this! Short of juggling panic hooks though I think we will have to upstream something
