### ISSUE TITLE
Not able to build crate with semver_exempt and --target flag passed

### ISSUE THREAD

**Issue by pepsighan** [alexcrichton/proc-macro2#131]
I need to build a macro for wasm usage which requires `semver_exempt`ed features. I am not able to run correctly `RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build --target wasm32-unknown-unknown`. The RUSTFLAGS is being ignored.  It seems to be due to [this](https://github.com/rust-lang/cargo/issues/4423).

Is there a way to get around this or provide an alternative feature flag (if nothing else possible)?

**Comment by csharad** [comment]
From the other thread.
> @rbalicki2 ... Currently if you're cross compiling you'll want to configure CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS=... as an environment variable or configure the [target.x86_64-unknown-linux-gnu.rustflags] key in .cargo/config.

I have tried this and other combination of flags from command line as well as from the .cargo/config, nothing works.

**Comment by alexcrichton** [comment]
Are you compiling from Linux? The `x86_64-unknown-linux-gnu` target will need to change depending on what platform you're running rustc on.

**Comment by csharad** [comment]
Yeah I am compiling from Linux. I don't understand what you mean by 
> The x86_64-unknown-linux-gnu target will need to change depending ...

**Comment by alexcrichton** [comment]
The configuration of `[target.x86_64-unknown-linux-gnu.rustflags]` in theory should work pending bugs in Cargo, but that depends that `rustc -vV` prints `host: x86_64-unknown-linux-gnu`. If that prints something else you'll need to change the configuration.

**Comment by csharad** [comment]
It prints the `host: x86_64-unknown-linux-gnu`.

**Comment by alexcrichton** [comment]
Ah then maybe this is a bug in Cargo? I'm not entirely sure :(

**Comment by csharad** [comment]
Should I file a bug in `rust`? I don't know what at all should be working. For me just a plain old `rustflags` should have worked.
For the time being I am using a patched `proc-macro2`.

**Comment by alexcrichton** [comment]
Perhaps! This probably requires a little more debugging to figure out where an issue goes. I don't know myself what to do with this issue.

**Comment by dtolnay** [comment]
If Alex isn't sure what to do here, this issue is no longer actionable, so I'll go ahead and close. Someone will need to debug this further as discussed above. If it turns out that some fix is necessary in this crate, feel free to open a PR or new issue then.
