### ISSUE TITLE
Travis build fails when using beta channel

### ISSUE THREAD

**Issue by xd009642** [alexcrichton/proc-macro2#132]
Firstly here is the travis run in question [link](https://travis-ci.org/xd009642/tarpaulin/jobs/426773415) the error says:

```
error[E0554]: #![feature] may not be used on the beta release channel
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.19/src/lib.rs:49:5
   |
49 | /     feature(proc_macro_raw_ident, proc_macro_span)
50 | | )]
   | |_^
```

I'll look into this myself but if anyone knows what the solution is that would be much appreciated :+1:

**Comment by alexcrichton** [comment]
Do you have `procmacro2_semver_exempt` specified as a cfg? That unfortunately makes it so this crate requires nightly.

**Comment by xd009642** [comment]
I do. However, it works on stable which is why I don't understand why beta fails :confused:

**Comment by alexcrichton** [comment]
Ah ok, that's because we're doing [automatic detection](https://github.com/alexcrichton/proc-macro2/blob/master/build.rs) of what compiler is in use, and opportunistically enabling the `proc_macro` crate linkage and APIs if the right compiler version is detected (which is beta and afterwards). Once 1.29.0 becomes stable this'll also break the stable build.

The feature story around proc-macro2 is a little bit muddied due to historical implementation shims, but we intend to require that the semver_exempt cfg requires nightly unconditionally.

**Comment by alexcrichton** [comment]
Sure yeah! The stabilizations here need to happen upstream in rust-lang/rust rather than here, so this probably also wants to be tracked upstream there. Unfortunately we haven't been super consistent about opening tracking issues for upstream rust-lang/rust and the `proc_macro` features, but we can start now!

**Comment by xd009642** [comment]
Sounds good to me if you point me in the right direction in rust-lang/rust I'll try my best to help. Having a brief search I couldn't see anything in issues but I might not be searching for the right stuff. https://github.com/rust-lang/rust/pull/49219 this looked relevant so wondering how this affects stabilisation once it's merged.

I'm aware this is probably getting offtopic so we can always move this somewhere else. I'm on the official rust-lang discord (I'm assuming `#compiler` is the relevant channel)

**Comment by alexcrichton** [comment]
Oh sure yeah, which parts of the unstable API are you interested in? (merging spans? hygiene? filenames? byte positions? etc...)

**Comment by xd009642** [comment]
Spans are probably the most interest to me. My own personal use makes a lot of use of Span::start() Span::end() (identifying lines of code that shouldn't be including in analysis)

**Comment by alexcrichton** [comment]
Ok cool, I don't think we have a preexisting dedicated tracking issue for that information but perhaps https://github.com/rust-lang/rust/issues/38546 can be used?

**Comment by xd009642** [comment]
I reckon there's definitely some overlap between my issue and that one. I'd only be concerned about hijacking djc's issue to work on things that may end up only being tangentially related. But if that's not an issue then sure thing.

**Comment by xd009642** [comment]
I was about to and having a look through issues etc and this seems to be an existing tracking issue that covers what I'd like to see stabilised https://github.com/rust-lang/rust/issues/38356 so I'm looking further into that right now

**Comment by xd009642** [comment]
@alexcrichton dunno if you want to open another issue but I now get this when I attempt to compile my project:

```
error[E0658]: use of unstable library feature 'proc_macro_def_site' (see issue #54724)                   
   --> /home/xd009642/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.19/src/unstable.rs:481:27
    |                                                                                                    
481 |             Span::Nightly(proc_macro::Span::def_site())                                            
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                               
    |                                                                                                    
    = help: add #![feature(proc_macro_def_site)] to the crate attributes to enable                       
```

**Comment by xd009642** [comment]
So @alexcrichton  I'm going to close this issue, the new tracking issues you opened solve my previously mentioned issue upstream and my new thing is sorted. Of course feel free to reopen if you think this is still useful to have around  :+1:
