### ISSUE TITLE
Ident is !Sync

### ISSUE THREAD

**Issue by mathstuf** [alexcrichton/proc-macro2#133]
…due to the `PhantomData<Rc<()>>`. I presume it is `!Sync` for a reason though…but this isn't documented anywhere that I can see.

**Comment by dtolnay** [comment]
The compiler's [`Ident`](https://doc.rust-lang.org/proc_macro/struct.Ident.html) is an index into a thread-local string interner, so cannot be accessed from a different thread. The `Ident` in proc-macro2 needs to expose the same API even if the implementation is currently different.

**Comment by mathstuf** [comment]
OK, thanks for the details.

**Comment by dtolnay** [comment]
Reopening to track explaining this in documentation.
