### ISSUE TITLE
Access to internal TokenTree Items

### ISSUE THREAD

**Issue by zjijz** [alexcrichton/proc-macro2#136]
**Use case**: I am trying to use Rust as the implementation for an initial compiler. My desire is to take an AST representing the (new) language constructs (represented by Rust structs) to generate different Rust structs and implementations to assist in the code generation step.

**Train of though**: Using the `quote` crate (which internally uses `TokenStream` defined in this crate), I will iterate over my AST and generate the necessary structs and methods. Right now, I want to translate this `TokenStream` back into a string that can be dumped into a Rust file. This specific process has the advantage of allowing me to transition to procedural macros and eliminate the need for an intermediate file stage at some point in the future if it would be useful (and `proc_macro` stabilizes).

**Issue**: There is currently no way to access the internals of `TokenStream` or `TokenTree` due to the private `proc_macro2::imp` indirection layer.

**Work-around**: For the meantime, I am probably going to try to apply regex's to the formatted `TokenTree` debug strings, but this is brittle and hacky.

Let me know if this was never an intention of `TokenStream`, but in my mind it seems useful to be able to programmatically use `TokenStream`s for more than just procedural macros. Also, I have no idea if `rustc` has a similar functionality to what I want already so please point me in that direction if it exists.

**Comment by zjijz** [comment]
Any of the actual symbol information. Right now, I can only know that an `Ident` or other type was matched. I can't actually get to the internal values since they are implemented on `proc_macro2::imp::Ident`. which is a private struct member of `proc_macro2::Ident`.

**Comment by dtolnay** [comment]
What do you mean by internal values? The text of the identifier?

The `Ident` documentation shows an example of accessing the value of an identifier as a string.
https://docs.rs/proc-macro2/0.4.19/proc_macro2/struct.Ident.html

**Comment by zjijz** [comment]
Oh, whoops. I forgot to try printing without the extra formatting information. I think everything I want is already there! Thank you!

**Comment by Venryx** [comment]
Assistance for other googlers, who want to use `TokenTree` entries in a `match`:
```
let token: &TokenTree = [...];
match token {
    TokenTree::Punct(data) if data.as_char() == '#' => [...],
    TokenTree::Group(data) if data.delimiter() == Delimiter::Bracket => [...],
    _ => [...],
}
```
