### ISSUE TITLE
Ident and raw_identifiers

### ISSUE THREAD

**Issue by haraldh** [alexcrichton/proc-macro2#140]
Is this supposed to work with rust-1.30, with https://github.com/rust-lang/rust/pull/53236/ merged ??

```
extern crate proc_macro2;
use proc_macro2::{Ident, Span};

fn main() {
    let _tname = Ident::new("r#enum", Span::call_site());
}
```
gives:
```
thread 'main' panicked at '"r#enum" is not a valid Ident'
[…]
   7: proc_macro2::stable::validate_term
             at […]/proc-macro2-0.4.20/src/stable.rs:580
[…]
```

**Comment by dtolnay** [comment]
I don't think so. You are going to need [`Ident::new_raw`](https://doc.rust-lang.org/nightly/proc_macro/struct.Ident.html#method.new_raw) once stabilized. For now I would recommend using syn:

```rust
let _tname: proc_macro2::Ident = syn::parse_str("r#enum").unwrap();
```
