### ISSUE TITLE
SourceFile needs to opt out of Send and Sync

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#141]
`proc_macro2::SourceFile` currently has both those traits. We need to opt out to match the one in the compiler:

https://github.com/rust-lang/rust/blob/1.30.0/src/libproc_macro/lib.rs#L419-L422

**Comment by eddyb** [comment]
In general, none of the types in the `proc_macro` public API that has any private state should be `Send`/`Sync`.
