### ISSUE TITLE
Consider failing loudly when RUSTC is unset in build.rs

### ISSUE THREAD

**Issue by thoughtpolice** [alexcrichton/proc-macro2#153]
NixOS Linux has support for Cargo and Rust through a few "build support" subsystems. One of these subsystems has a bug we recently discovered: https://github.com/NixOS/nixpkgs/pull/50452

The TL;DR is this: we accidentally failed to set `RUSTC` when running the `build.rs` scripts for Cargo packages, which is [supposed to be available when Cargo runs the build itself](https://doc.rust-lang.org/cargo/reference/environment-variables.html) (we don't use Cargo for this step, ourselves). The failure to do this is, of course, wrong, and it caused a failure in `proc_macro2`.

However, when I debugged and figured this out, it lead me to believe that this particular bizarre corner case could also be handled better by `proc-macro2`.

The build failure looked something like this:

  - I depend on something that needs `proc-macro2`. In this case, that was [syn](https://github.com/dtolnay/syn)
  - It wants to use the `proc-macro` feature of `proc-macro2`, because it wants the `From` trait impl for the `TokenStream` type, [which is defined here](https://github.com/alexcrichton/proc-macro2/blob/f6674da9ab419923c605165e88dd571c83821f74/src/stable.rs#L122). `syn` [uses that impl here](https://github.com/dtolnay/syn/blob/6bd3e03c3d1407d0b77f93844bea1ff26ba3a28c/src/buffer.rs#L115)
  - That impl is guarded in `proc-macro2` by `#[cfg(use_proc_macro)]`
  - That config setting is emitted at runtime by `build.rs`
  - We try to build `proc-macro2` to satisfy `syn`'s dependency, and we set the `proc-macro` feature to be enabled.
  - We run `build.rs`, *but we do not set `RUSTC`*. This causes the `rustc_minor_version` function to return `None`: https://github.com/alexcrichton/proc-macro2/blob/f6674da9ab419923c605165e88dd571c83821f74/build.rs#L59
  - Because it returns `None`, the `build.rs` script **silently exits without reporting anything**. However, **it does this before it can output `cargo:rustc-cfg=use_proc_macro`** https://github.com/alexcrichton/proc-macro2/blob/f6674da9ab419923c605165e88dd571c83821f74/build.rs#L10-L22
  - This means that `cfg(use_proc_macro)` now fails, because Cargo did not detect it in the `build.rs` output, but also, `build.rs` completed successfully.
  - The `From` impl for `TokenStream` is now not compiled into the resulting library.
  - Building `syn` now mysteriously fails, because the `From` trait is not satisfied, even though it said it should be in its dependencies.

---

I am not an experienced Rust programmer, but it seems like this is an obvious bug: **build.rs should fail if `RUSTC` is unset**, because it can lead to very bizarre build failures for downward dependencies, due to configuration options not being set.

Now, there is the possibility that it would be useful to run the compiled build script *outside* of Cargo occasionally, and setting `RUSTC` would make that annoying. In fact, that's how I discovered this bug -- but on the other hand, there's already a panic that happens if `TARGET` is unset, and that is also set by Cargo! So it seems like handling one case but not the other in a consistent manner has no benefits?

The second thing is, the emission of the `cargo:rustc-cfg=use_proc_macro` directive **could be lifted above the check for the `RUSTC` variable**. This would have also prevented *this* particular bug, but it also means that e.g. support for `u128` would not have been compiled in, even though we use Rust 1.30 in our build system! That could have resulted in an identical failure anyway, e.g. a downstream consumer demands `proc-macro2` the same way `syn` did, and it does a similar check (or, it might, more silently dictate that it only works on Rust 1.26+ *anyway* and then just *assume* `u128` is there with no conditional!)

---

Failing fast here would have saved a bit of time debugging/reverse engineering this failure on the NixOS side of things (although that is wholly our problem -- we specifically go around Cargo in a few ways), but it seems like it's a strict improvement for an obviously erroneous case, that otherwise leads to spurious downstream build errors. Better safe than sorry, and all that!

**Comment by alexcrichton** [comment]
Unfortunately this is required because this snippet is intended to handle backwards compatibility with older rustc implementations, but older Cargo implementations didn't set RUSTC. The lack of RUSTC is a proxy for "this is too old to handle"

**Comment by thoughtpolice** [comment]
Just catching up here: thanks for the explanation! That's unfortunate but since nothing can be done, I'll close this. (Luckily it's at least linked back to the issue in our repo)

**Comment by donovanglover** [comment]
Spent hours trying to figure out why my Tauri apps would always have random ld errors and narrowed it down to proc-macro2 and subsequently this issue.

This has to be one of the most obscure bugs I've encountered. I added `export RUSTC="rustc"` to my `flake.nix` and it worked, however when I ran `nix flake update` everything broke again (even after downgrading and running `cargo clean`).
