### ISSUE TITLE
partialEq for Span

### ISSUE THREAD

**Issue by pkpkpk** [alexcrichton/proc-macro2#154]
This was added in #68 and has since been removed. Can it be re-introduced or put under a flag?

**Comment by dtolnay** [comment]
We follow the API of the compiler's `proc_macro::Span`. It looks like `proc_macro::Span` had PartialEq back when #68 was merged but [no longer does](https://doc.rust-lang.org/nightly/proc_macro/struct.Span.html). Could you help track down where it was removed upstream to confirm the reason?

**Comment by pkpkpk** [comment]
Ok I will try!

**Comment by pkpkpk** [comment]
Looks like it was removed here: [reorganize public API ](https://github.com/rust-lang/rust/commit/553c04d9eb311189cbd01d1af7f6c2c26578342c#diff-9ea37887c69f218bed1798983de82b79)

**Comment by dtolnay** [comment]
Could you say more about your use case for this impl? Then we can check with alexcrichton or petrochenkov how we can support that use case. What is your code doing that needs PartialEq on Span?

**Comment by pkpkpk** [comment]
I am trying to write fixtures and tests for some parsing code similar to [wasm-bindgen's parser](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/macro-support/src/parser.rs#L226). Incidentally, the removal of partialeq breaks WB's 'extra-traits' feature.

**Comment by dtolnay** [comment]
Is there any meaning to comparing the spans in that case, or is it only to make it convenient to derive PartialEq rather than implement by hand in a way that ignores spans?

**Comment by dtolnay** [comment]
Closing as this was rejected in https://github.com/rust-lang/rust/pull/59070.
