### ISSUE TITLE
impl std::ops::Add for TokenStream 

### ISSUE THREAD

**Issue by diwic** [alexcrichton/proc-macro2#157]
The following code:

    let mut x = quote! {
        fn dummy() {}
    };
    if some_condition { x += quote! {
        fn dummy2() {} 
    } };

Fails with:

    error[E0369]: binary operation `+` cannot be applied to type `proc_macro2::TokenStream`

Maybe it's me not understanding TokenStreams, but I intuitively expected this to work and get a `TokenStream` containing ` fn dummy() {}  fn dummy2() {}` (if `some_condition` is true)?

(It's possible to use strings instead of tokenstreams, but that loses span information I believe?)

**Comment by dtolnay** [comment]
TokenStream is more like Vec than like String. Vec also does not support `+=`.

```rust
let mut v = vec![1, 2];
v += vec![3, 4];
```

You can use interpolation:

```rust
x = quote! {
    #x
    fn dummy2() {} 
}
```

or `Extend`:

```rust
x.extend(quote! {
    fn dummy2() {} 
});
```

**Comment by diwic** [comment]
Thanks!
