### ISSUE TITLE
Span::unstable doesn't work in test mode

### ISSUE THREAD

**Issue by asomers** [alexcrichton/proc-macro2#159]
Proc macro diagnostics are great!  But oddly, they don't seem to work in test mode.  My proc macro crate enables the "nightly" feature for proc-macro2, and its diagnostics work fine when I force an error in an integration test.  But in my unit tests I always get a 'stable/nightly mismatch' error.  Here's an example.  Stick this in the lib directory of a proc macro crate that uses proc-macro2's nightly feature, and it will print the same error:
```rust
#[test]
fn stable_nightly_mismatch() {
    Span::call_site().unstable().error("xxx").emit()
}
```

**Comment by dtolnay** [comment]
This is intentional -- proc_macro::Span can't exist outside of a procedural macro. I clarified this in the documentation in #160.

**Comment by asomers** [comment]
Thanks for the quick fix.
