### ISSUE TITLE
Ident exposing allocation free &str

### ISSUE THREAD

**Issue by theypsilon** [alexcrichton/proc-macro2#170]
I noticed that Ident has to go through to_string for exposing its contained value. That seems to allocate memory, but please, correct me if I'm wrong. I've been checking the rust code and it leads me to String::fmt calling Display::fmt. So my question is easy, in the case that I'm not wrong, why isn't there a way to return an str without extra memory allocations. Thanks!

**Comment by alexcrichton** [comment]
Currently there's no way to access the value of an `Ident` without allocating, no. It's not currently planned for upstream `proc-macro` itself, but it's flexible! Is the profiling motivation perhaps for removing the allocation?

**Comment by dtolnay** [comment]
I have not seen this allocation appear significant when profiling Syn. Parsing involves looking at every identifier so I believe it would show up if the allocation were a bottleneck.

Separately, note that in the case of proc macros, allocating a string takes basically zero time compared to compiling all of the generated code. Compiling the generated code probably takes 6-7 orders of magnitude longer than making a String from every Ident in the macro input. So the optimization suggested in this issue would only possibly improve compile time by something like 0.00001%.

**Comment by theypsilon** [comment]
No, I haven't done any profiling. Since one of the goals of this crate was bringing proc_macro to other unknown use cases, and one of the rust signatures is zero-cost abstractions, I thought it might be natural to have it in the API. But of course, I see that it could make a lot of sense that the codebase can't afford a new method without real numbers backing it.

Thanks for taking your time responding me, I didn't know that in proc macros, working through the parsed TokenStream would have so little impact in performance compared to compiling the generated TokenStream. That's very interesting.

**Comment by dtolnay** [comment]
I'll close for now but let's revisit if anyone has a benchmark where this is significant for their use case.
