### ISSUE TITLE
Provide way to disable `nightly` cfg

### ISSUE THREAD

**Issue by Nemo157** [alexcrichton/proc-macro2#175]
In `futures` we're attempting to treat the nightly compiler as stable [using `RUSTFLAGS="-Z allow-features="`](https://github.com/rust-lang-nursery/futures-rs/blob/master/.travis.yml#L74) to ensure future compatibility with Rust 1.36. Unfortunately this is [failing in CI](https://travis-ci.com/rust-lang-nursery/futures-rs/jobs/196052814#L537) because of `proc-macro2` unconditionally activating its own `nightly` cfg and attempting to use an unstable feature.

It would be great if we could somehow disable this feature no matter what channel of Rust we happen to be building with.

**Comment by dtolnay** [comment]
I would accept a PR to parse RUSTFLAGS in our build script and look for whether proc_macro_span is present in `allow-features`.

If that won't work, alternatively we could expose an opt-out through RUSTFLAGS:

```console
RUSTFLAGS='--cfg no_opportunistic_nightly'
```

**Comment by Nemo157** [comment]
Parsing `RUSTFLAGS` sounds reasonable if the build script has access to it, I’ll take a look at doing that tomorrow.
