### ISSUE TITLE
Add From<proc-macro2::Span> for proc-macro::Span 

### ISSUE THREAD

**Issue by CreepySkeleton** [alexcrichton/proc-macro2#181]
Well, one could do 

```rust
fn span2_to_span(span: proc_macro2::Span) -> Span {
    use proc_macro2::{TokenTree as TokenTree2, Ident as Ident2, TokenStream as TokenStream2};

    let ident = Ident2::new("foo", span);
    let tt = TokenTree2::Ident(ident);
    let iter = std::iter::once(tt);
    let ts = TokenStream2::from_iter(iter);
    let ts = TokenStream::from(ts);
    let ident = ts.into_iter().next().unwrap();
    ident.span()
}
```

But some more direct approach would be useful

**Comment by dtolnay** [comment]
Could you explain more about the use case where this is necessary? Typically macros that use proc-macro2 would do everything in terms of proc-macro2 types, with only a conversion from proc_macro::TokenStream at the very beginning and a conversion to proc_macro::TokenStream at the very end.

**Comment by CreepySkeleton** [comment]
This is not strictly necessary. I just happened to have a need to build a `proc-macro::TokenStream` by hand (I admit my codebase could use some refactoring) hence the need to such a conversion. It is not a typical use case. I just don't see any reason why not to have a standard solution

**Comment by dtolnay** [comment]
Makes sense -- I would recommend building a proc_macro2::TokenStream instead and using that conversion if necessary. I believe it would be best to keep only our current set of conversions (TokenStream only). Mixing types from the two libraries quickly gets complicated and is always better written using a TokenStream conversion.

**Comment by Qix-** [comment]
I'm trying to add `Diagnostic` support to `syn` and the inability to convert between `proc_macro2` and `proc_macro` spans is a blocker.

I was looking into a `From` implementation, but it appears there's no way to construct a `proc_macro::Span` on its own - it _must_ come from a token. `proc_macro` itself would have to be modified to support this usecase.
