### ISSUE TITLE
Should not be unit structs

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#2]
The current stable imp contains:

```rust
pub struct LexError;
pub struct Span;
```

These should be structs with a private field to match the ones in proc_macro. That way users can't write code that works with stable but not unstable.

**Comment by alexcrichton** [comment]
Oh these shouldn't be reexported directly but rather [contained in the top level](https://github.com/alexcrichton/proc-macro2/blob/master/src/lib.rs#L22-L23) in an opaque way? Did I reexport something though by accident?

**Comment by dtolnay** [comment]
Oh you're right! Never mind.
