### ISSUE TITLE
proc_macro2 v1.0.5 is missing on docs.rs

### ISSUE THREAD

**Issue by CreepySkeleton** [alexcrichton/proc-macro2#203]
That's what I see when I hit the "Go to latest version" button

![image](https://user-images.githubusercontent.com/50968528/67150606-5713bf80-f2c2-11e9-896f-5297d6cbd3c4.png)

**Comment by dtolnay** [comment]
Thanks, this looks like a docs.rs or rustwide issue. I filed https://github.com/rust-lang/docs.rs/issues/440 to follow up.

**Comment by CreepySkeleton** [comment]
[It looks like it was fixed.](https://github.com/rust-lang/docs.rs/issues/440#issuecomment-571581119)
