### ISSUE TITLE
Should `RUSTFLAGS='--cfg procmacro2_semver_exempt'` actually create a useful API?

### ISSUE THREAD

**Issue by hgomersall** [alexcrichton/proc-macro2#204]
I'm trying to access a the filename of the calling code through `Span::call_site().source_file()`. This works fine on nightly, but on stable with  `RUSTFLAGS='--cfg procmacro2_semver_exempt'`, the call to `source_file()` returns something like `SourceFile { path: "<unspecified>", is_real: false }`, which is clearly not useful.

Should the call to `source_file()` work as expected (i.e. returning the filename), or is this just a place holder API?

**Comment by mystor** [comment]
There is no way to get this information from the compiler when running without access to nightly features, so we have to use a "default" value. It isn't possible for us to return the "real" call-site without the corresponding rust features being stabilized.

**Comment by hgomersall** [comment]
That makes sense, thanks!
