### ISSUE TITLE
expose mixed_site macro_rules hygeine

### ISSUE THREAD

**Issue by CAD97** [alexcrichton/proc-macro2#210]
rustc impl: https://github.com/rust-lang/rust/pull/64690  
tracking issue: https://github.com/rust-lang/rust/issues/65049

**Comment by m1el** [comment]
It seems like both linked tickets got resolved.  Any updates on this?
https://github.com/rust-lang/rust/pull/64690
https://github.com/rust-lang/rust/pull/68716
