### ISSUE TITLE
Travis builds aren't running...?

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#222]
In https://travis-ci.com/github/alexcrichton/proc-macro2/builds it looks like Travis stopped doing our cron and PR builds since March 3:

<br>

![Screenshot from 2020-05-01 16-54-51](https://user-images.githubusercontent.com/1940490/80849562-7faf3700-8bcc-11ea-872a-12ac63cc3e8d.png)

<br>

even though all the configuration looks good and there is a daily always-run cron scheduled; it is apparently next scheduled to run "in 2 months ago":

<br>

![Screenshot from 2020-05-01 16-55-27](https://user-images.githubusercontent.com/1940490/80849576-935a9d80-8bcc-11ea-8cc5-cb6a4c304cad.png)

**Comment by dtolnay** [comment]
I tried manually triggering a build and something unknown went wrong.

<br>

![Screenshot from 2020-05-01 17-05-24](https://user-images.githubusercontent.com/1940490/80849902-19c3af00-8bce-11ea-9764-a851df1b7057.png)

<br>

![Screenshot from 2020-05-01 17-04-30](https://user-images.githubusercontent.com/1940490/80849905-1cbe9f80-8bce-11ea-8dea-c696a0a7e655.png)

**Comment by alexcrichton** [comment]
I think I likely broke this, I'll look to switch to GitHub actions on Monday
