### ISSUE TITLE
Non-ascii characters in doc comments offsets are miscounted

### ISSUE THREAD

**Issue by jrvidal** [alexcrichton/proc-macro2#227]
```rust
let stream: TokenStream = FromStr::from_str("//! a").unwrap();
for tree in stream {
    eprintln!("{:?}", tree.span().end());
}

let stream: TokenStream = FromStr::from_str("//! Ø").unwrap();
for tree in stream {
    eprintln!("{:?}", tree.span().end());
}
```

prints:
```
LineColumn { line: 1, column: 5 }
LineColumn { line: 1, column: 5 }
LineColumn { line: 1, column: 5 }
LineColumn { line: 1, column: 6 }
LineColumn { line: 1, column: 6 }
LineColumn { line: 1, column: 6 }
```

I suspect the problem is [here](https://github.com/alexcrichton/proc-macro2/blob/3f9b24d63611b82d9378c6d794dd93ef6007a79d/src/parse.rs#L760), where the cursor is advanced using byte positions instead of character positions.

**Comment by botika** [comment]
`Span` counts bytes not characters

**Comment by jrvidal** [comment]
I was under the impression that `LineColumn.column` is character-based, not byte-based: https://docs.rs/proc-macro2/1.0.13/proc_macro2/struct.LineColumn.html

IIRC, the mismatch does not occur if you change the doc comments with explicit doc attributes.

**Comment by botika** [comment]
if we count in characters, in which byte is the "a" in this text? 

`"ØØaØ"` `LineColumn { line: 1, column: 2 }`

How do we mark the snippets in each line? With an oracle?

**Comment by dtolnay** [comment]
I would accept a PR to fix this to match libproc_macro's behavior, which is character based.

**Comment by jrvidal** [comment]
I'll give it a try

**Comment by botika** [comment]
https://github.com/botika/proc-macro2/blob/master/src/fallback.rs#L407-L422
If all I have are the byte of the line, and a range. @dtolnay  I ask the same thing again, are you going to implement an oracle, or realloc the text, or past text as argument? I honestly don't understand. I will learn a lot with the solution.

**Comment by dtolnay** [comment]
@botika you need the text anyway in order to turn line+column into a byte offset in the file. Once you have source text, adding up the byte size of the first N characters on a line to get a byte offset is not hard.

**Comment by botika** [comment]
https://github.com/botika/proc-macro2/blob/master/src/fallback.rs#L325-L346
When you create the cursor, then there is no text to look at this on.

https://github.com/botika/proc-macro2/blob/master/src/fallback.rs#L305
The only thing it keeps is the line number. Do you want to convert that line number to utf-8 first and then measure utf-8 in the parser. 
It is quite expensive and it does not affect the `compile_error!`, in addition to not being able to know the byte with the `LineColumn` output, the only output there is.

Come on you break me `yarte`.

**Comment by dtolnay** [comment]
> When you create the cursor, then there is no text to look at this on.

Your link is to private implementation code inside proc-macro2. Yes, fixing the bug means changing code, possibly including that code.

**Comment by botika** [comment]
Ok, the implementation of `Span` in utf-8 characters, I'll find a solution to frame it with the bytes. Thank you. See you.
