### ISSUE TITLE
force_fallback produce invalid span

### ISSUE THREAD

**Issue by botika** [alexcrichton/proc-macro2#274]
In yarte@0.15, related https://github.com/botika/yarte/issues/211

With parse impl of `syn::Expr`:
```rust
ywrite_html!(buf, "{{ @ }}");
```
works correctly, error is spammed by syn with fallback span.

And for this with `Punctuated::parse_terminated`:
```rust
ywrite_html!(buf, r#"{{> hello_ex my_card body="foo" }}"#);
```
not works, panic with `Invalid span with no related FileInfo!`

**Comment by dtolnay** [comment]
Would you be able to provide a minimal repro using proc-macro2 only, independent of yarte and syn?

**Comment by botika** [comment]
It is much more complicated than I expected, I cannot replicate it separately. It will take a little longer. 

On the other hand, I got `stable / nightly mismatch`  panic in the `trybuild` tests of yarte. 


The implementation is very stable but from the error messages it seems that it operates with both types of Span when it should be forced to fallback. 

I will try to reproduce it but it will take a little longer.

**Comment by dtolnay** [comment]
I'll close this in the absence of a way to reproduce. Feel free to open a new issue if you nail down what's happening.
