### ISSUE TITLE
Use proc_macro's impl FromStr for Literal once Rust 1.53 is stable

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#287]
In #286, we implemented `impl FromStr for Literal` in terms of `impl FromStr for TokenStream`. The upstream PR https://github.com/rust-lang/rust/pull/84717 adds a real `impl FromStr for Literal` to libproc_macro; we should use it once available in a release.

**Comment by houqp** [comment]
@dtolnay we are getting a compilation error with the latest proc-macro2 release:

```
error[E0599]: no function or associated item named `from_str` found for struct `proc_macro::Literal` in the current scope
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.29/src/wrapper.rs:926:38
    |
926 |                 proc_macro::Literal::from_str(repr)
    |                                      ^^^^^^^^ function or associated item not found in `proc_macro::Literal`


error: aborting due to previous error


For more information about this error, try `rustc --explain E0599`.

error: could not compile `proc-macro2`
```

Full run error can be accessed at https://github.com/apache/arrow-datafusion/runs/3472141634.

Could you give some tips on how to workaround this problem?

**Comment by smoelius** [comment]
For me, using toolchain `nightly-2021-05-21` [made the problem go away](https://github.com/dtolnay/proc-macro2/issues/297#issuecomment-909283849).

**Comment by houqp** [comment]
Thanks @smoelius , if I read the code correctly, it should work for stable rust version >= 1.53. But we are still getting the error with rust 1.54, so I feel like something is off here.
