### ISSUE TITLE
`arbitrary` support

### ISSUE THREAD

**Issue by CraftSpider** [alexcrichton/proc-macro2#288]
Would there be any interest in adding support for the `arbitrary` crate, under a feature flag, to support fuzz-testing proc-macros? Note that arbitrary token streams are likely not very useful, but I have interest in adding the same support to `syn`, which would allow the easy creation of arbitrary-but-valid AST nodes. However this first requires support for arbitrary Idents/Literals/etc.

I would be willing to make the PR to add all this, but wanted to ask whether there would be any interest in supporting it first.

**Comment by dtolnay** [comment]
I am not interested in accepting `arbitrary` impls into syn so I will go ahead and close this, because as you said arbitrary token streams on their own are not useful.
