### ISSUE TITLE
How do you detect if the code is compiled as a proc-macro?

### ISSUE THREAD

**Issue by notdanilo** [alexcrichton/proc-macro2#289]
Sorry for creating an issue for it. But I have been googling about it with no success and I believe proc_macro2 does something similar.

I need to implement `TryFrom<proc_macro::TokenStream>` only if `proc_macro` is available. I looked at the code but it wasn't clear for me how it is done.

**Comment by dtolnay** [comment]
As far as I know, there isn't a way.

**Comment by notdanilo** [comment]
@dtolnay but how does proc_macro2 `impl From<proc_macro::TokenStream> for proc_macro2::TokenStream`?

**Comment by dtolnay** [comment]
Unconditionally regardless of whether proc-macro2 is depended on by any proc macros.

**Comment by dtolnay** [comment]
More generally it seems like what you are looking for incompatible with how Cargo builds work. Suppose we have:

```
notdanilo (binary)
├── libnotdanilo (proc macro)
└───└── proc-macro2
```

where the binary depends on proc-macro2 directly, and also on a proc macro that depends on proc-macro2. It sounds like you are expecting for this build to make 2 separate builds of proc-macro2, one with a From impl to be used by libnotdanilo, and another without a From impl to be used by the binary. That isn't the case, it is built only once, at least when the target and host architecture are the same i.e. when not cross-compiling. So there is no such thing as conditional compilation depending on whether some downstream crate is a macro.

**Comment by notdanilo** [comment]
OK. I was definitely missing something here. I was assuming it was impossible to use the `proc_macro` crate outside a proc-macro. But it looks like I can also import the `proc_macro` crate if I use `extern crate proc_macro;`. Also: The `proc_macro` crate is automatically imported when compiling proc-macros.

I stopped using `extern crate` once it was deprecated, but I remember that this is one of the fews use cases that it was still needed.

**Comment by notdanilo** [comment]
@dtolnay thanks for your time btw! :)
