### ISSUE TITLE
Arbitrary precision literals

### ISSUE THREAD

**Issue by andy-thomason** [alexcrichton/proc-macro2#291]
More of a question than an issue.

I am building a computer algebra system focused on replacing libm using syn/quote.

Although I can create literals of arbitrary accuracy (100 digit floats for example) the
tokens that accompany them seem to be limited to f64.

It there an easy way to generate an `ExprLit` in syn with the appropriate proc-macro2
token?

**Comment by dtolnay** [comment]
I am not sure what you tried but it doesn't matter to `ExprLit` how many digits there are.

```rust
// [dependencies]
// quote = "1.0"
// syn = "1.0"

use quote::quote;
use syn::ExprLit;

fn main() {
    let digits = "0.101001000100001000001000000100000001000000001000000000100000000001000000000001000000000000100000000000001";
    let lit: ExprLit = syn::parse_str(digits).unwrap();
    println!("{}", quote!(#lit));
}
```

output:

```console
0.101001000100001000001000000100000001000000001000000000100000000001000000000001000000000000100000000000001
```

**Comment by andy-thomason** [comment]
Thanks for getting back to me. I have to add that syn/quote have been invaluable tools in
my recent work with R integration and maths library generation.

It seems the problem is with syn, specifically `to_literal` in `lit.rs`

The problem also only manifests on negative numbers which are treated
differently.

```
fn main() {
    let s = "-3.123456789123456789123456789";
    let lit = syn::LitFloat::new(s, proc_macro2::Span::call_site());
    println!("lit={:?}", lit);
}
```

Truncates, but

```
fn main() {
    let s = "3.123456789123456789123456789";
    let lit = syn::LitFloat::new(s, proc_macro2::Span::call_site());
    println!("lit={:?}", lit);
}
```

Does not!

In your example,  adding a leading "-" also manifests the problem.

**Comment by dtolnay** [comment]
As far as I know negative literals only exist so that Literal construction from f64 can avoid being crashy. They are not meant to be used outside of that. `-3.123456789123456789123456789` is 2 tokens in Rust.

```rust
macro_rules! count_tokens {
    ($($tt:tt)*) => { 0 $(+ {stringify!($tt); 1})* };
}

fn main() {
    println!("{}", count_tokens!(-3.123456789123456789123456789));
}
```

```console
2
```

You should use ExprUnary to negate a literal token.

```rust
use quote::quote;
use syn::Expr;

fn main() {
    let digits = "-0.101001000100001000001000000100000001000000001000000000100000000001000000000001000000000000100000000000001";
    let lit: Expr = syn::parse_str(digits).unwrap();
    println!("{}", quote!(#lit));
}
```

```console
- 0.101001000100001000001000000100000001000000001000000000100000000001000000000001000000000000100000000000001
```

**Comment by andy-thomason** [comment]
This sounds like a good working solution. I'll open the definition of a result to include negation.
Rationals are also possible with divide.
