### ISSUE TITLE
Force fallback can be disabled from another macro

### ISSUE THREAD

**Issue by botika** [alexcrichton/proc-macro2#295]
proc-macro2 should handle static variables per thread, using the `thread_local` macro. Forcing `fallback` and working multiple macros with inputs to the io, slow operations, a datarace state is produced. If `Span` structures cannot be moved to other threads, the `fallback` should also be handled per thread as it is the only different element in the result. 

https://github.com/alexcrichton/proc-macro2/blob/b128cd6cfd5647da1cb2f74295ea076515eb8174/src/detection.rs#L5

i.e., the `WORKS` flag is changed in the middle of a macro with a long process. You should use `thread_local` to statically allocate `WORKS`

**Comment by dtolnay** [comment]
This is not a supported use of force fallback. It is intended for use in bin crates -- in which case the libproc_macro API is not available whatsoever (in any thread).
