### ISSUE TITLE
A compiler error started to appear after 1.0.29

### ISSUE THREAD

**Issue by rimbi** [alexcrichton/proc-macro2#297]
```
error[E0599]: no function or associated item named `from_str` found for struct `proc_macro::Literal` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.29/src/wrapper.rs:926:38
    |
926 |                 proc_macro::Literal::from_str(repr)
    |                                      ^^^^^^^^ function or associated item not found in `proc_macro::Literal`
```

Compiler version: `rustc 1.54.0-nightly (79e50bf77 2021-05-10)`

Any idea?

**Comment by taiki-e** [comment]
I think you need to use the newer nightly toolchain.

**Comment by rimbi** [comment]
This seems quite reasonable but it causes other compiler errors in other crates. :)

**Comment by rimbi** [comment]
The workaround is to revert back to the previous version:
```
cargo update -p proc-macro2 --precise 1.0.28
```

**Comment by smoelius** [comment]
FWIW, here is where `proc_macro::Literal::from_str` is implemented: https://github.com/rust-lang/rust/commit/34585cb678bc492be7e48ff48a2633f4ce1dc5ae

And `nightly-2021-05-21` seems to be the earliest toolchain with that commit.

**Comment by mikevoronov** [comment]
Today and we stumbled on this problem. I'm just wondering why not increase a minor crate version?

**Comment by dtolnay** [comment]
This crate does not support old nightly compilers. In general it is not reasonable to expect crates to support arbitrary old nightly compilers.

**Comment by houqp** [comment]
@dtolnay I am getting this error with rust 1.54 too, is this expected?

**Comment by vasilakisfil** [comment]
Same here, running `rustc 1.54.0 (a178d0322 2021-07-26)` and whichever version I am trying (1.0.27, 1.0.28 or 1.0.29) I get the same error.
