### ISSUE TITLE
Crate almost compiles... (OSX box, )

### ISSUE THREAD

**Issue by gilescope** [alexcrichton/proc-macro2#32]
Seems to have stopped compiling with the last couple of weeks nighties on OSX:

error[E0277]: the trait bound `proc_macro::Span: std::default::Default` is not satisfied
   --> /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.1.3/src/unstable.rs:163:17
    |
163 | pub struct Span(proc_macro::Span);
    |                 ^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `proc_macro::Span`
    |
    = note: required by `std::default::Default::default`

Any suggestions to get it working again?

**Comment by mystor** [comment]
You're using proc-macro2 v0.1.3, which is out of date. Try updating to the latest version v0.1.5.

**Comment by alexcrichton** [comment]
Indeed!

**Comment by gilescope** [comment]
Many Thanks - I tried proc-macro2 = { version = "0.1", features = ["unstable"] } but that didn't pick it up. Specifying 0.1.5 worked nicely though.
