### ISSUE TITLE
Way to get the type of literal

### ISSUE THREAD

**Issue by antoyo** [alexcrichton/proc-macro2#33]
Hi.
Currently, the structure of [`Literal`](https://github.com/alexcrichton/proc-macro2/blob/e6085b71802f21a9c5429af0a8b56e916c20c48a/src/lib.rs#L180) is private.
Could you please add a way to inspect the literals?
Thank you.

**Comment by dtolnay** [comment]
For now check out [`literalext`](https://github.com/mystor/literalext).

**Comment by alexcrichton** [comment]
Yeah currently this crate is mirroring the `proc_macro` crate upstream as much as possible which [unfortunately has no accessors](https://github.com/rust-lang/rust/blob/9c49f401fecd8c5ef42a33a070a61daa2b911b47/src/libproc_macro/lib.rs#L445-L512) so for now literalext is the way to go!
