### ISSUE TITLE
Get the span of an Expr

### ISSUE THREAD

**Issue by antoyo** [alexcrichton/proc-macro2#34]
Hi.
Is there an easy way to get the `Span` of an `Expr`?
That is without having to use pattern matching on `node` and getting the span manually.
Thank you.

**Comment by alexcrichton** [comment]
Hm is this maybe more of an issue for `syn`? This crate doesn't actually have an `Expr`...

**Comment by antoyo** [comment]
Oh, sorry.
Wrong repository.
