### ISSUE TITLE
Rename either --cfg procmacro2_unstable or --features proc-macro2/unstable

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#42]
These are basically orthogonal flags so it is confusing to give them such similar names. Someone may want to use procmacro2_unstable without proc-macro2/unstable to get the emulation of line and column from #36 on the stable compiler, or may want to use proc-macro2/unstable without procmacro2_unstable to get real spans without the semver-exempt APIs.

**Comment by alexcrichton** [comment]
How about changing the Cargo feature to `nightly` or `rustc-nightly`?

**Comment by dtolnay** [comment]
:+1: for either of those. I might go with `--cfg procmacro2_semver_exempt` and `--features proc-macro2/nightly`.

Want me to do proc-macro2 0.2 with a semver-trick to bridge 0.1's `unstable` feature to 0.2's `nightly` feature? Or go to 0.2 without a semver-trick? Or just make both changes in 0.1 because :shipit:?

**Comment by mystor** [comment]
Yeah - sorry about the bad naming. I wasn't a big fan of it at the time either :-/.

I called it `procmacro2_unstable` to match the `rayon_unstable` cfg flag which rayon uses: https://github.com/rayon-rs/rayon#semver-policy-the-rayon-core-crate-and-unstable-features

**Comment by alexcrichton** [comment]
@dtolnay I'd personally be ok with just shipping everything in 0.1 (e.g. just commenting that a feature is disabled in `Cago.toml`), and I'd be fine to rename the `--cfg` whenever!

**Comment by alexcrichton** [comment]
(also the names you proposed seemed fine by me, if you're gonna send a PR feel free to decide!)
