### ISSUE TITLE
Any breaking changes lined up?

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#43]
I am getting ready to cut a Syn major version later this week with proc-macro2 in its public API. If we are planning to do any breaking changes in the near term, this would be the best time.

**Comment by alexcrichton** [comment]
AFAIK no but @mystor do you have something you'd like?

**Comment by mystor** [comment]
I don't think I have any super big changes which I want to land which would be practical to land soon, so I think we can just go for it.

**Comment by dtolnay** [comment]
Thanks!
