### ISSUE TITLE
Remove impl Default for Span

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#48]
This was removed upstream in https://github.com/rust-lang/rust/pull/45999. As discussed in https://github.com/rust-lang/rust/issues/45934#issuecomment-344497531, there isn't really anything more "default" about `def_site` over `call_site`.

Worth changing before the syn 0.12 release before more people start banging on this stuff?

**Comment by alexcrichton** [comment]
I originally just switched it over to avoid the breaking change, but `syn` is looking so polished nowadays I'd hate for this be a blemish! I'm game for making an 0.2 release with this change.
