### ISSUE TITLE
Trim down and reduce compile times

### ISSUE THREAD

**Issue by mystor** [alexcrichton/proc-macro2#5]
Right now `proc-macro2` stable makes up a decent amount of the build time for syn-master. 

It shouldn't be too hard to strip down its dependencies and make the parsing code compile a bit faster, especially once #4 lands.

**Comment by alexcrichton** [comment]
Are you thinking of any particularly high priority piece? Wins in compile times nowadays are gained generally from "compile less code" but I'm not sure how much we can remove from this crate...

**Comment by mystor** [comment]
No, I don't think this is super high priority. I think I just remembered seeing the `stable` implementation doing some unnecessary work while parsing which we could potentially get away without. Nothing in specific.

**Comment by dtolnay** [comment]
I'll go ahead and close since this issue does not seem particularly actionable or useful to remain open. I would still welcome any PRs to help compile time in this or related crates.
