### ISSUE TITLE
#[proc_macro] with proc-macro2

### ISSUE THREAD

**Issue by ignatenkobrain** [alexcrichton/proc-macro2#53]
I'm trying to make one library to compile with proc-macro2 in order to use it without nightly rust, but I can't find replacement for `#[proc_macro]` attribute. Is there any? Or how am I supposed to do it?

Thanks a lot in advance!

**Comment by dtolnay** [comment]
This crate does not provide a replacement for #[proc_macro]. The closest thing would be [`proc-macro-hack`](https://github.com/dtolnay/proc-macro-hack).

**Comment by mystor** [comment]
The current stable use of this crate is to implement custom derives, which can be implemented using Macros 1.1.

Generalized procedural macros are currently unstable.
