### ISSUE TITLE
Enabling "nightly" feature breaks processing of mod in another file

### ISSUE THREAD

**Issue by CodeSandwich** [alexcrichton/proc-macro2#56]
# Situation
`my_mod` is a module with body in file `my_mod.rs`. To include it in the project it must be declared in another file, let's say `lib.rs`. I'm trying to push whole `my_mod` into proc macro `my_macro`, so I write in `lib.rs`:
```
#[my_macro]
mod my_mod;
```
# Without "nightly" feature
Whole content of `my_mod` is passed into macro.
# With "nightly" feature
Only `mod my_mod;` is passed into macro.
# Question
Is it regression or is it the way proc macros 2.0 are supposed to work?

**Comment by mystor** [comment]
This sounds like a rustc issue - I'm not sure. It's surprising that the `to_string` method would produce such a dramatically different result than the TokenStream.

**Comment by dtolnay** [comment]
I don't think we can fix this in proc-macro2 so I filed https://github.com/rust-lang/rust/issues/47627 to follow up in the compiler. Thanks!

**Comment by CodeSandwich** [comment]
Thank you for investigation and filing a root cause issue!
