### ISSUE TITLE
Custom derive could not find trait when build with nightly feature

### ISSUE THREAD

**Issue by csharad** [alexcrichton/proc-macro2#66]
I have the following custom derive implemented for `Component` trait. When I used it without `nightly` feature it works. But with it, it errors out with `cannot find trait Component in this scope`. I would like to use nightly feature for handling and showing errors for `#[proc_macro]`. Is this bug or intended? Or am I doing something wrong?

```#[proc_macro_derive(Component)]
pub fn derive_component(input: TokenStream) -> TokenStream {
    let ast: syn::DeriveInput = syn::parse(input).unwrap();
    let tokens = impl_component(&ast);
    tokens.into()
}

fn impl_component(ast: &syn::DeriveInput) -> quote::Tokens {
    let name = ast.ident;
    quote! {
        impl Component for #name {
            fn component(&self) -> &str {
                "Hello World"
            }
        }
    }
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! This is due to the hygiene in the compiler, so you'll either need to work around that (like in https://github.com/dtolnay/syn/blob/master/examples/heapsize2/heapsize_derive/src/lib.rs) or you'll need to use `quote_spanned!` with the `Span::call_site()` span
