### ISSUE TITLE
Span::def_site is missing :(

### ISSUE THREAD

**Issue by SeunLanLege** [alexcrichton/proc-macro2#78]
@dtolnay

https://docs.rs/proc-macro2/0.3.6/proc_macro2/struct.Span.html

the futures await crate used it in version 0.2, and in 0.3 it's gone :disappointed:

**Comment by dtolnay** [comment]
It looks like `def_site` is not going to be stabilized in the first round of libproc_macro stabilizations. If you really want to experiment with it anyway, it is behind the semver exempt flag as described [here](https://github.com/alexcrichton/proc-macro2/tree/0.3.6#unstable-features).
