### ISSUE TITLE
Distributing binary built with `procmacro2_semver_exempt`

### ISSUE THREAD

**Issue by xd009642** [alexcrichton/proc-macro2#89]
I've got a project that's using `syn 0.3.8` with `procmacro2_semver_exempt`. I tried doing `cargo install` from the git repo/branch and it attempted to build without the rustflags in `.cargo/config` so the build failed. Obviously, this behaviour isn't desired as a user shouldn't have to specify `RUSTFLAGS` before running `cargo install` so I'm wondering if this is still the case when installing from `crates.io` and if there is any advice for more easily distributing my binary?

**Comment by alexcrichton** [comment]
Ah unfortuately the best way here is probably going to be prebuilt binaries, I don't think Cargo reads .cargo/config of crates being installed to learn about these variables

**Comment by xd009642** [comment]
Damn, that throws a spanner in the works... Would it be possible for syn to allow a more "dangerous" cfg option to enable semver exempt functionality and warn users that they should specify major.minor.patch otherwise `cargo update` may break users projects?

I'm going to open an issue on cargo to see if there' any interest in allowing people to optionally include the contents of `.cargo/config` when running `cargo publish` or specifying a config file in the `Cargo.toml` as I can't believe I'm the only user that would want this.

**Comment by alexcrichton** [comment]
Perhaps? The point of the `procmacro2_semver_exempt` is to explicitly be difficult to use. That way it puts pressure on actively designing and stabilizing features

**Comment by xd009642** [comment]
I understand the rationale and appreciate it, this is really because my hand is slightly forced by a dependency on `syntex_syntax` now causing panics with some new rust syntax (nested paths in use statements). To replicate the functionality I'm moving to `syn` and require the `Span::start()` and `Span::end()` functions which are semver exempt. 

Also, as people run my project in their CI via cargo install, I'd prefer if the update was painless and didn't require any intervention on their parts. I do have docker images and prebuilt binaries for travis so it won't effect everyone but it's still an issue.

As an aside I have been jotting some thoughts about the API for interacting with Span's in an issue I raised in syn https://github.com/dtolnay/syn/issues/406 . Generally, I'm happy with `start()` and `end()` and the `LineColumn` struct though another user would prefer zero indexing

**Comment by dtolnay** [comment]
The procmacro2_semver_exempt gate is no longer required for Span::start and Span::end as of proc-macro2 0.4.27. Hopefully that makes it easier to experiment with these methods in real code. Span start and end were the main use case brought up in this thread, so I will go ahead and close.
