### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/proc-macro2#9]
Things we want in proc-macro that are not in https://github.com/rust-lang/rust/pull/40939:

- [ ] Debug impls for the public types. Because debugging this stuff is hard enough even when you understand what the input contains.

**Comment by mystor** [comment]
I'm going to add my wishlist:
[ ] Methods on `Literal` to interpret the types into useful values (like `as_u64(&self) -> Option<u64>`) - This should probably be done behind a config flag to save on compile time.
[ ] A similar method on `Symbol` to ask if its a lifetime or an identifier.

**Comment by dtolnay** [comment]
> This should probably be done behind a config flag to save on compile time.

I would not worry about compile time. When this is stabilized, compile time for proc-macro will not factor in to compile time for crates. I would prefer to have a usable API even if in the interim proc-macro2 is slow.

**Comment by mystor** [comment]
I was more thinking in terms of syn doesn't need that API and neither do most of the current proc macro consumers. If we decide to ship a TokenStream based syn before proc-macro is stabilized then we'll want to not regress build speeds.

**Comment by Arnavion** [comment]
>I was more thinking in terms of syn doesn't need that API and neither do most of the current proc macro consumers.

Hmm, I need it for my proc macro to be able to parse attributes like `#[my_macro(foo = "bar", baz = false, quux = 0)]` and get the value of the `foo`, `baz`, `quux` properties. I think this would be a very common requirement?

**Comment by TedDriggs** [comment]
@Arnavion just found this comment: I've been working on a library that's "serde-for-proc-macros", called [`darling`](https://docs.rs/darling). It does exactly what you mentioned your need is here, in a way that - in my opinion - ends up being more idiomatic.

**Comment by dtolnay** [comment]
This issue is from many iterations of proc_macro ago. I'll go ahead and close; let's reflect and then file individual follow-ups as needed.
