### ISSUE TITLE
Convenience trait implementations on `Ident`

### ISSUE THREAD

**Issue by hcpl** [alexcrichton/proc-macro2#93]
Should `Ident` from `proc-macro2` 0.4 have following trait implementations [like `Ident` from `syn` 0.13](https://docs.rs/syn/0.13/syn/struct.Ident.html#implementations)?
- `From<&'a str>`;
- `From<Cow<'a, str>>`;
- `From<String>`;
- `AsRef<str>` (however this one makes `impl PartialEq<T: AsRef<str> + ?Sized>` conflict with `impl PartialEq`).

Also in case of the last one, is a quote from: https://github.com/rust-lang/rust/pull/50473
> - Removed APIs: Ident::as_str, use Display impl for Ident instead.

relevant here (as in `Ident::as_str` being equivalent to `<Ident as AsRef<str>>::as_ref`)?

**Comment by alexcrichton** [comment]
The ones missing now are `From` and it's an explicit design decision of `proc_macro` the crate to always require spans to be specified when creating an `Ident`. I'd like to stick with that for now before we add `From` implementations which implicitly choose a span for you

**Comment by dtolnay** [comment]
Regarding `AsRef`: the compiler folks are not comfortable committing to an API that does &Ident ⟶ &str. https://github.com/rust-lang/rust/issues/38356#issuecomment-386786645 explains.

`From`: over time these spans will get more important and we would prefer to require them explicitly.

**Comment by hcpl** [comment]
Thank you for the explanation. I was just concerned about the effort needed to port from the old `proc-macro` & `quote` & `syn` stack, but keeping API minimal is important too, so that's fine.

**Comment by hcpl** [comment]
I suppose `name` is an `Ident`. In that case, you can use
```rust
let _name = Ident::new(&name.to_string(), Span::call_site());
```
instead. [Example on playground](https://play.rust-lang.org/?gist=cb43e801abd482e6216c0339d3c650f4&version=stable&mode=debug).

**Comment by chocol4te** [comment]
Thank you so much! :)
